config/routes.rb
Rails.application.routes.draw do
  resources :dashes do
    resources :metrics
  end

  root 'home#index'

end

app/models/dash.rb
class Dash < ActiveRecord::Base
  has_many :dash_metrics
  has_many :metrics, through: :dash_metrics
end

app/models/dash_metric.rb
class DashMetric < ActiveRecord::Base
  belongs_to :dash
  belongs_to :metric
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  has_many :dash_metrics

  enum widget_type: { widget_image: 0, widget_iframe: 1, widget_json: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashes_controller.rb
class DashesController < ApplicationController
  before_action :set_dash, only: [:show, :edit, :update, :destroy]

  # GET /dashes
  # GET /dashes.json
  def index
    @dashes = Dash.all
  end

  # GET /dashes/1
  # GET /dashes/1.json
  def show
    @metrics = @dash.metrics
  end

  # GET /dashes/new
  def new
    @dash = Dash.new
  end

  # GET /dashes/1/edit
  def edit
  end

  # POST /dashes
  # POST /dashes.json
  def create
    @dash = Dash.new(dash_params)

    respond_to do |format|
      if @dash.save
        format.html { redirect_to @dash, notice: 'Dash was successfully created.' }
        format.json { render :show, status: :created, location: @dash }
      else
        format.html { render :new }
        format.json { render json: @dash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashes/1
  # PATCH/PUT /dashes/1.json
  def update
    respond_to do |format|
      if @dash.update(dash_params)
        format.html { redirect_to @dash, notice: 'Dash was successfully updated.' }
        format.json { render :show, status: :ok, location: @dash }
      else
        format.html { render :edit }
        format.json { render json: @dash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashes/1
  # DELETE /dashes/1.json
  def destroy
    @dash.destroy
    respond_to do |format|
      format.html { redirect_to dashes_url, notice: 'Dash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dash
      @dash = Dash.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dash_params
      params.require(:dash).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_action :set_dash
  before_action :set_metric, only: [:show, :edit, :update, :destroy]

  # GET /metrics
  # GET /metrics.json
  def index
    @metrics = @dash.metrics
  end

  # GET /metrics/1
  # GET /metrics/1.json
  def show
  end

  # GET /metrics/new
  def new
    @metric = Metric.new
  end

  # GET /metrics/1/edit
  def edit
  end

  # POST /metrics
  # POST /metrics.json
  def create
    @metric = Metric.new(metric_params)

    respond_to do |format|
      if @metric.save
        @dash.metrics << @metric
        format.html { redirect_to @dash, notice: 'Metric was successfully created.' }
        format.json { render :show, status: :created, location: @metric }
      else
        format.html { render :new }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metrics/1
  # PATCH/PUT /metrics/1.json
  def update
    respond_to do |format|
      if @metric.update(metric_params)
        format.html { redirect_to @dash, notice: 'Metric was successfully updated.' }
        format.json { render :show, status: :ok, location: @metric }
      else
        format.html { render :edit }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.json
  def destroy
    @metric.destroy
    respond_to do |format|
      format.html { redirect_to @dash, notice: 'Metric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metric
      @metric = Metric.find(params[:id])
    end

    def set_dash
      @dash = Dash.find(params[:dash_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metric_params
      params.require(:metric).permit(:title, :widget_type, :widget_data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashes_helper.rb
module DashesHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/dashes/_dash_item.html.erb
<% metric = dash.metrics.first %>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= link_to dash.name, dash %>
    </h3>
  </div>
  <div class="panel-body">
    <% if metric.present? %>
      <% if metric.widget_image? %>
        <%= image_tag metric.widget_data, class: "img-responsive" %>
      <% else %>
        <div class="embed-responsive embed-responsive-4by4">
          <%= raw metric.widget_data %>
        </div>
      <% end %>
    <% else %>
      <%= image_tag "http://placeholdit.imgix.net/~text?txtsize=33&txt=New-Dash&w=550&h=550", class: "img-responsive" %>
    <% end %>
  </div>
</div>

app/views/dashes/_form.html.erb
<%= form_for @dash,  html: { class: "form-vertical" } do |f| %>
  <% if @dash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dash.errors.count, "error") %> prohibited this dash from being saved:</h2>

      <ul>
      <% @dash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-12">
    <div class="form-group">
      <%= f.label :name, "Dash Title", class: "control-label" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Title for the dash" %>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="form-group">
      <%= f.label :refresh_interval, "Dash Refresh Interval (in milliseconds)", class: "control-label" %>
      <%= f.text_field :refresh_interval, class: "form-control", placeholder: "Default: 10000" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-12">
      <div class="pull-right">
        <%= link_to "Cancel", dashes_path, class: "btn btn-link btn-sm" %>
        <%= f.submit "Save", class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashes/edit.html.erb
<h1>Editing Dash</h1>

<%= render 'form' %>

<%= link_to 'Show', @dash %> |
<%= link_to 'Back', dashes_path %>

app/views/dashes/index.html.erb
<% content_for :page_title do %>
  Dashboards
<% end %>

<% content_for :page_actions do %>
  <p class="pull-right">
    <%= link_to "Create New Dash", new_dash_path, class: "btn btn-default btn-sm" %>
  </p>
<% end %>

<div class="row">
  <% @dashes.each do |dash| %>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      <%= render 'dash_item', dash: dash %>
    </div>
  <% end %>
</div>

app/views/dashes/new.html.erb
<% content_for :page_title do %>
  New Dash
<% end %>

<% content_for :page_actions do %>
  <p class="pull-right">
  <%= link_to 'Back', dashes_path, class: "btn btn-default btn-sm" %>
  </p>
<% end %>

<%= render 'form' %>

app/views/dashes/show.html.erb
<% content_for :page_title do %>
  <%= @dash.name %>
<% end %>

<% content_for :page_actions do %>
  <p class="pull-right">
  <%= link_to "Add New Widget", new_dash_metric_path(@dash), class: "btn btn-default btn-sm" %>
  <%= link_to 'Edit', edit_dash_path(@dash), class: "btn btn-warning btn-sm" %>
  <%= link_to 'Back', dashes_path, class: "btn btn-default btn-sm" %>
  </p>
<% end %>

<div id="metrics">
  <%= render '/metrics/metrics', metrics: @metrics, dash: @dash %>
</div>

<% content_for :js do %>
  var refreshWidgets = function() {
    $(".metric-widget").each(function(index) { 
      widget_url = $(this).data("url");
      widget_refreshable = $(this).data("refreshable");
      console.log(widget_refreshable);
      if(widget_refreshable == "1") {
        $.getScript(widget_url);
      }
    });
  };
<% end %>

<% content_for :onload_js do %>
  $.getScript("<%= dash_metrics_path(@dash) %>");

  setInterval(function () {
    refreshWidgets();
    console.log("Refreshed");
  }, <%= @dash.refresh_interval || 10000 %>);
<% end %>

app/views/home/index.html.erb
List of dashboards

app/views/layouts/_header.html.erb
asdfsd
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "DashWgt", dashes_path, class: "navbar-brand" %>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
        </li>
        <li>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      </ul>

    </div>
  </div>
</div>

app/views/layouts/_js.html.erb
<script type="text/javascript">

  <%= yield :js %>

  var ajax_loader = "<%= j image_tag "ajax-loader.gif" %>";

  $(document).ready(function(){
    <%= yield :onload_js %>
  });

  <%# for turbolink page load event %>
  $(document).on("page:load", function(){
    <%# yield :onload_js %>
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Dashm</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-8 col-md-7 col-sm-6">
            <h1><%= yield :page_title %></h1>
            <p class="lead"></p>
          </div>
          <div class="col-lg-4 col-md-5 col-sm-6">
            <div class="sponsor">
              <%= yield :page_actions %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
  <%= render '/layouts/js' %>
</html>

app/views/metrics/_form.html.erb
<%= form_for [@dash, @metric],  html: { class: "form-horizontal" } do |f| %>
  <% if @metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% @metric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Widget Title", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control", placeholder: "Eg: Prod-App Memory Usage" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :widget_type, "Widget Type", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <div class="radio">
        <label>
          <%= f.radio_button :widget_type, "widget_image" %>
          Use Image URL realtime
          Use Image URL realtime. <small>Eg: http://graphite.prod.ch4.s.com/render?target=servers.xxapp1.vmstats.memUsedPct&height=800&width=600</small> 
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :widget_type, "widget_iframe" %>
          Use iFrame to render HTML widget. <small>Eg: <%= "<iframe src=\"https://rpm.newrelic.com/public/charts/894U680X2dC1\"></iframe>" %></small>
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :widget_type, "widget_json" %>
          Use JSON URL realtime. <small>Eg: http://graphite.prod.ch4.s.com/render?target=servers.xxapp1.vmstats.memUsedPct&format=json</small> 
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :widget_data, "Widget Image URL or iFrame", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :widget_data, class: "form-control", placeholder: "Eg: http://graphite.prod.ch4.s.com/render?target=servers.xxapp1.vmstats.memUsedPct&height=800&width=600", rows: 2 %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-12">
      <div class="pull-right">
        <%= link_to "Cancel", @metric.persisted? ? dash_metric_path(@dash, @metric) : dash_metrics_path(@dash), class: "btn btn-link btn-sm" %>
        <%= f.submit "Save", class: "btn btn-default" %>
      </div>
    </div>
  </div>

<% end %>

app/views/metrics/_metric_item.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= link_to metric.title, [@dash, metric] %>
    </h3>
  </div>
  <div class="panel-body">
    <% if metric.widget_image? %>
      <%= image_tag metric.widget_data, class: "img-responsive" %>
    <% else %>
      <div class="embed-responsive embed-responsive-4by4">
        <%= raw metric.widget_data %>
      </div>
    <% end %>
  </div>
</div>

app/views/metrics/_metrics.html.erb
<% if metrics.present? %>
  <div class="row">
    <% metrics.each do |metric| %>
      <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 metric-widget" data-url="<%= dash_metric_path(dash, metric) %>" data-refreshable="<%= metric.widget_iframe? ? 0 : 1 %>" id="metric-<%=metric.id%>">
        <%= render '/metrics/metric_item', metric: metric %>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="lead">No widgets added to this dash</p>
<% end %>

app/views/metrics/edit.html.erb
<% content_for :page_title do %>
  Edit Widget
<% end %>

<% content_for :page_actions do %>
  <p class="pull-right">
  <%= link_to 'Show', [@dash, @metric], class: "btn btn-default btn-sm" %>
  <%= link_to 'Back', dash_metrics_path(@dash), class: "btn btn-default btn-sm" %>
  </p>
<% end %>

<%= render 'form' %>

<hr />

app/views/metrics/index.html.erb
<% content_for :page_title do %>
  <%= @dash.name %>
<% end %>

<% content_for :page_actions do %>
  <p class="pull-right">
  <%= link_to "Add New Widget", new_dash_metric_path(@dash), class: "btn btn-default btn-sm" %>
  </p>
<% end %>

<div class="row">
  <% @metrics.each do |metric| %>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      <%= render 'metric_item', metric: metric %>
    </div>
  <% end %>
</div>

app/views/metrics/index.js.erb
$("#metrics").html("<%= j render '/metrics/metrics', metrics: @metrics, dash: @dash %>");

app/views/metrics/new.html.erb
<% content_for :page_title do %>
  New Widget
<% end %>

<% content_for :page_actions do %>
  <p class="pull-right">
  <%= link_to 'Back', @dash, class: "btn btn-default btn-sm" %>
  </p>
<% end %>

<%= render 'form' %>

app/views/metrics/show.html.erb
<% content_for :page_title do %>
  <%= @metric.title %>
<% end %>

<% content_for :page_actions do %>
  <p class="pull-right">
    <%= link_to 'Back', dash_path(@dash), class: "btn btn-default btn-sm" %>
    <%= link_to 'Edit', edit_dash_metric_path(@dash, @metric), class: "btn btn-default btn-sm" %>
    <%= link_to 'Delete', dash_metric_path(@dash, @metric), method: :delete, class: "btn btn-danger btn-sm" %>
  </p>
<% end %>

<div class="row">
  <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12">
    <% if @metric.widget_image? %>
      <%= image_tag @metric.widget_data, class: "img-responsive" %>
    <% else %>
      <div class="embed-responsive embed-responsive-4by3">
        <%= raw @metric.widget_data %>
      </div>
    <% end %>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 clearfix">
    <div class="well well-sm clearfix">
      <p> <strong>Name:</strong> <%= @metric.title %> </p>
      <p style="text-wrap: none; word-wrap: break-word;"> <strong>Widget:</strong> <span> <%= @metric.widget_data %> </span></p>
    </div>
  </div>
</div>

app/views/metrics/show.js.erb
$("#metric-<%= @metric.id%>").html("<%= j render '/metrics/metric_item', metric: @metric, dash: @dash %>");